language: node_js
dist: xenial
node_js: lts/*
sudo: true

# limit the Travis 'build on push' feature to master branch only
branches:
  only:
   - master
   - /^greenkeeper/.*$/

install:
  - yarn install

script:
  - yarn lint

after_success:
  # run automated release process with semantic-release
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then
      yarn global add semantic-release@16.0.0-beta.18 @semantic-release/changelog@3 @semantic-release/exec@3.4.0-beta.2 @semantic-release/git@7.1.0-beta.3;
      semantic-release;
    fi;

notifications:
  email:
    on_success: never
